import type { PrinterModel, User } from "./types";

export const seedUsers: User[] = [
  {
    uid: "u_admin_rina",
    displayName: "Rina Ko",
    email: "rina@printforge.local",
    role: "admin",
    team: "Ops Systems",
    active: true,
  },
  {
    uid: "u_lead_marcus",
    displayName: "Marcus Hale",
    email: "marcus@printforge.local",
    role: "engineering_lead",
    team: "Manufacturing",
    active: true,
  },
  {
    uid: "u_eng_talia",
    displayName: "Talia Brooks",
    email: "talia@printforge.local",
    role: "engineer",
    team: "Prototype Lab",
    active: true,
  },
  {
    uid: "u_operator_ivy",
    displayName: "Ivy Chen",
    email: "ivy@printforge.local",
    role: "operator",
    team: "Print Room",
    active: true,
  },
];

export const printerCatalog: PrinterModel[] = [
  {
    modelId: "bambu_lab_a1",
    brand: "Bambu Lab",
    model: "A1",
    printerType: "fdm",
    technology: "FFF",
    iconKey: "printer-bambu-a1",
    buildVolume: [256, 256, 256],
    capabilityFlags: ["rapid-prototyping", "pla-petg-friendly", "open-bay"],
  },
  {
    modelId: "bambu_lab_p1s",
    brand: "Bambu Lab",
    model: "P1S",
    printerType: "fdm",
    technology: "FFF",
    iconKey: "printer-bambu-p1s",
    buildVolume: [256, 256, 256],
    capabilityFlags: ["enclosed", "production-cell", "multi-material-ready"],
  },
  {
    modelId: "bambu_lab_x1c",
    brand: "Bambu Lab",
    model: "X1C",
    printerType: "fdm",
    technology: "FFF",
    iconKey: "printer-bambu-x1c",
    buildVolume: [256, 256, 256],
    capabilityFlags: ["engineering-materials", "enclosed", "camera-ready"],
  },
  {
    modelId: "bambu_lab_x1e",
    brand: "Bambu Lab",
    model: "X1E",
    printerType: "fdm",
    technology: "FFF",
    iconKey: "printer-bambu-x1e",
    buildVolume: [256, 256, 256],
    capabilityFlags: ["chamber-heated", "enterprise-network", "engineering-materials"],
  },
  {
    modelId: "anycubic_kobra_s1",
    brand: "Anycubic",
    model: "Kobra S1",
    printerType: "fdm",
    technology: "FFF",
    iconKey: "printer-anycubic-kobra-s1",
    buildVolume: [250, 250, 250],
    capabilityFlags: ["enclosed", "corexy", "general-production"],
  },
  {
    modelId: "creality_k2_plus",
    brand: "Creality",
    model: "K2 Plus",
    printerType: "fdm",
    technology: "FFF",
    iconKey: "printer-creality-k2-plus",
    buildVolume: [350, 350, 350],
    capabilityFlags: ["large-format", "multi-color-ready", "production-builds"],
  },
  {
    modelId: "sovol_sv08",
    brand: "Sovol",
    model: "SV08",
    printerType: "fdm",
    technology: "FFF",
    iconKey: "printer-sovol-sv08",
    buildVolume: [350, 350, 345],
    capabilityFlags: ["large-format", "open-source-friendly", "corexy"],
  },
  {
    modelId: "elegoo_saturn_4_ultra_16k",
    brand: "Elegoo",
    model: "Saturn 4 Ultra 16K",
    printerType: "resin",
    technology: "MSLA",
    iconKey: "printer-elegoo-saturn-4-ultra-16k",
    buildVolume: [211.68, 118.37, 220],
    capabilityFlags: ["resin-only", "high-resolution", "wash-cure-workflow"],
  },
];
