import type {
  ActivityEvent,
  Blocker,
  BuildJob,
  FileRevision,
  Material,
  Printer,
  Project,
  User,
} from "./types";

export const seedUsers: User[] = [
  {
    uid: "u_admin_rina",
    displayName: "Rina Ko",
    email: "rina@printforge.local",
    role: "admin",
    team: "Ops Systems",
    active: true,
  },
  {
    uid: "u_lead_marcus",
    displayName: "Marcus Hale",
    email: "marcus@printforge.local",
    role: "engineering_lead",
    team: "Manufacturing",
    active: true,
  },
  {
    uid: "u_eng_talia",
    displayName: "Talia Brooks",
    email: "talia@printforge.local",
    role: "engineer",
    team: "Prototype Lab",
    active: true,
  },
  {
    uid: "u_eng_owen",
    displayName: "Owen Park",
    email: "owen@printforge.local",
    role: "engineer",
    team: "Prototype Lab",
    active: true,
  },
  {
    uid: "u_operator_ivy",
    displayName: "Ivy Chen",
    email: "ivy@printforge.local",
    role: "operator",
    team: "Print Room",
    active: true,
  },
  {
    uid: "u_viewer_sam",
    displayName: "Sam Ortiz",
    email: "sam@printforge.local",
    role: "viewer",
    team: "Program Management",
    active: true,
  },
];

export const seedPrinters: Printer[] = [
  {
    printerId: "printer_a1_bay3",
    brand: "Bambu Lab",
    model: "A1",
    nickname: "A1 Bay 3",
    printerType: "fdm",
    technology: "FFF",
    location: "Prototype Bay",
    operationalStatus: "available",
    queueStatus: "open",
    iconKey: "printer-bambu-a1",
    buildVolume: [256, 256, 256],
    capabilityFlags: ["flexibleMaterialFriendly", "cameraSupported"],
    utilizationToday: 31,
  },
  {
    printerId: "printer_p1s_cell2",
    brand: "Bambu Lab",
    model: "P1S",
    nickname: "P1S Cell 2",
    printerType: "fdm",
    technology: "FFF",
    location: "Production Cell A",
    operationalStatus: "busy",
    queueStatus: "2 queued",
    currentJobId: "job_jig_244",
    iconKey: "printer-bambu-p1s",
    buildVolume: [256, 256, 256],
    capabilityFlags: ["enclosed", "multiMaterialCapable", "cameraSupported"],
    utilizationToday: 82,
  },
  {
    printerId: "printer_x1c_lab1",
    brand: "Bambu Lab",
    model: "X1C",
    nickname: "X1C Lab 1",
    printerType: "fdm",
    technology: "FFF",
    location: "Materials Lab",
    operationalStatus: "reserved",
    queueStatus: "priority slot",
    iconKey: "printer-bambu-x1c",
    buildVolume: [256, 256, 256],
    capabilityFlags: ["enclosed", "engineeringMaterialFriendly", "cameraSupported"],
    utilizationToday: 68,
  },
  {
    printerId: "printer_x1e_ops",
    brand: "Bambu Lab",
    model: "X1E",
    nickname: "X1E Ops",
    printerType: "fdm",
    technology: "FFF",
    location: "Ops Lab",
    operationalStatus: "maintenance",
    queueStatus: "service window",
    iconKey: "printer-bambu-x1e",
    buildVolume: [256, 256, 256],
    capabilityFlags: ["enclosed", "chamberHeated", "networkManaged"],
    utilizationToday: 14,
  },
  {
    printerId: "printer_k2_plus",
    brand: "Creality",
    model: "K2 Plus",
    nickname: "K2 Plus LF",
    printerType: "fdm",
    technology: "FFF",
    location: "Large Format Row",
    operationalStatus: "busy",
    queueStatus: "1 queued",
    currentJobId: "job_fixture_991",
    iconKey: "printer-creality-k2-plus",
    buildVolume: [350, 350, 350],
    capabilityFlags: ["largeFormat", "multiMaterialCapable"],
    utilizationToday: 91,
  },
  {
    printerId: "printer_sv08",
    brand: "Sovol",
    model: "SV08",
    nickname: "SV08 Alpha",
    printerType: "fdm",
    technology: "FFF",
    location: "Large Format Row",
    operationalStatus: "paused",
    queueStatus: "investigating layer shift",
    currentJobId: "job_cover_731",
    iconKey: "printer-sovol-sv08",
    buildVolume: [350, 350, 345],
    capabilityFlags: ["largeFormat", "engineeringMaterialFriendly"],
    utilizationToday: 47,
  },
  {
    printerId: "printer_saturn4",
    brand: "Elegoo",
    model: "Saturn 4 Ultra 16K",
    nickname: "Saturn Resin 1",
    printerType: "resin",
    technology: "MSLA",
    location: "Resin Room",
    operationalStatus: "busy",
    queueStatus: "wash/cure follow-up",
    currentJobId: "job_lens_842",
    iconKey: "printer-elegoo-saturn-4-ultra-16k",
    buildVolume: [211.68, 118.37, 220],
    capabilityFlags: ["resinMachine", "cameraSupported"],
    utilizationToday: 76,
  },
];

export const seedMaterials: Material[] = [
  {
    materialId: "mat_seed_bambu_pla_basic",
    brandId: "brand_bambu_lab",
    brandName: "Bambu Lab",
    familyId: "PLA",
    displayName: "PLA Basic",
    productLine: "Basic",
    resinOrFilament: "filament",
    status: "standard",
    validationState: "seeded",
    diameter: 1.75,
    color: "Signal White",
    compatiblePrinterIds: ["printer_a1_bay3", "printer_p1s_cell2"],
    useCount: 42,
    notes: "General-purpose baseline material for fixtures and visual prototypes.",
  },
  {
    materialId: "mat_seed_bambu_petg_hf",
    brandId: "brand_bambu_lab",
    brandName: "Bambu Lab",
    familyId: "PETG_HS",
    displayName: "PETG HF",
    productLine: "HF",
    resinOrFilament: "filament",
    status: "approved",
    validationState: "approved",
    diameter: 1.75,
    color: "Industrial Gray",
    compatiblePrinterIds: ["printer_p1s_cell2", "printer_x1c_lab1"],
    useCount: 28,
    notes: "Standard functional-print line for brackets, jigs, and enclosures.",
  },
  {
    materialId: "mat_seed_polymaker_pla_pro",
    brandId: "brand_polymaker",
    brandName: "Polymaker",
    familyId: "PLA_PRO",
    displayName: "PLA Pro",
    productLine: "PLA Pro",
    resinOrFilament: "filament",
    status: "standard",
    validationState: "seeded",
    diameter: 1.75,
    color: "Black",
    compatiblePrinterIds: ["printer_a1_bay3", "printer_p1s_cell2", "printer_k2_plus"],
    useCount: 24,
    notes: "Reliable mid-strength filament for design verification runs.",
  },
  {
    materialId: "mat_seed_fiberon_pa6_cf20",
    brandId: "brand_fiberon",
    brandName: "Fiberon by Polymaker",
    familyId: "PA6_CF",
    displayName: "Fiberon PA6-CF20",
    productLine: "Fiberon",
    resinOrFilament: "filament",
    status: "experimental",
    validationState: "under_review",
    diameter: 1.75,
    reinforcement: "carbon fiber",
    requiresDrying: true,
    compatiblePrinterIds: ["printer_x1c_lab1", "printer_x1e_ops"],
    useCount: 9,
    notes: "High-rigidity engineering filament. Drying and hardened nozzle warnings required.",
  },
  {
    materialId: "mat_seed_esun_pla_plus",
    brandId: "brand_esun",
    brandName: "eSUN",
    familyId: "PLA_PLUS",
    displayName: "PLA+",
    productLine: "PLA+",
    resinOrFilament: "filament",
    status: "standard",
    validationState: "seeded",
    diameter: 1.75,
    color: "Blue",
    compatiblePrinterIds: ["printer_a1_bay3", "printer_sv08"],
    useCount: 15,
    notes: "Fast-availability stock for internal concept builds.",
  },
  {
    materialId: "resin_siraya_fast_gray",
    brandId: "brand_siraya_tech",
    brandName: "Siraya Tech",
    familyId: "FAST_MODEL",
    displayName: "Siraya Tech Fast",
    productLine: "Fast",
    resinOrFilament: "resin",
    status: "standard",
    validationState: "seeded",
    color: "Smoky Gray",
    compatiblePrinterIds: ["printer_saturn4"],
    useCount: 18,
    notes: "Rapid concept resin for detail validation and fit checks.",
  },
  {
    materialId: "resin_siraya_blu_clear",
    brandId: "brand_siraya_tech",
    brandName: "Siraya Tech",
    familyId: "TOUGH",
    displayName: "Siraya Tech Blu",
    productLine: "Blu",
    resinOrFilament: "resin",
    status: "approved",
    validationState: "approved",
    color: "Clear",
    compatiblePrinterIds: ["printer_saturn4"],
    useCount: 11,
    notes: "Engineering resin for durable parts and clear housings.",
  },
  {
    materialId: "resin_siraya_tenacious_black",
    brandId: "brand_siraya_tech",
    brandName: "Siraya Tech",
    familyId: "FLEXIBLE",
    displayName: "Siraya Tech Tenacious",
    productLine: "Tenacious",
    resinOrFilament: "resin",
    status: "experimental",
    validationState: "under_review",
    color: "Black",
    compatiblePrinterIds: ["printer_saturn4"],
    useCount: 6,
    notes: "Flexible blend-capable resin under validation for impact-heavy parts.",
  },
  {
    materialId: "resin_siraya_magna_gray",
    brandId: "brand_siraya_tech",
    brandName: "Siraya Tech",
    familyId: "TOUGH",
    displayName: "Siraya Tech Magna",
    productLine: "Magna",
    resinOrFilament: "resin",
    status: "standard",
    validationState: "seeded",
    color: "Gray",
    compatiblePrinterIds: ["printer_saturn4"],
    useCount: 7,
    notes: "Durable resin line for small functional components.",
  },
];

export const seedProjects: Project[] = [
  {
    projectId: "proj_jig_panel",
    title: "Panel Alignment Jig",
    code: "PF-2417",
    description: "Repeatable assembly alignment jig for electronics chassis validation.",
    priority: "high",
    status: "printing",
    ownerUid: "u_eng_talia",
    collaboratorUids: ["u_lead_marcus", "u_operator_ivy"],
    requestedMaterialId: "mat_seed_bambu_petg_hf",
    preferredPrinterIds: ["printer_p1s_cell2", "printer_x1c_lab1"],
    dueDate: "2026-04-26T17:00:00+09:00",
    tags: ["fixture", "rush", "assembly"],
    blocked: false,
    archived: false,
    progress: 72,
    currentRevisionLabel: "r5 approved_current",
    printerTargetId: "printer_p1s_cell2",
    latestActivityAt: "2026-04-24T08:40:00+09:00",
  },
  {
    projectId: "proj_fixture_large",
    title: "Large Fixture Nest",
    code: "PF-2418",
    description: "Large-format holding nest for thermal-cycling fixture prep.",
    priority: "critical",
    status: "queued",
    ownerUid: "u_eng_owen",
    collaboratorUids: ["u_lead_marcus", "u_operator_ivy"],
    requestedMaterialId: "mat_seed_polymaker_pla_pro",
    preferredPrinterIds: ["printer_k2_plus", "printer_sv08"],
    dueDate: "2026-04-25T13:00:00+09:00",
    tags: ["large-format", "fixture"],
    blocked: true,
    archived: false,
    progress: 54,
    currentRevisionLabel: "r3 ready",
    printerTargetId: "printer_k2_plus",
    latestActivityAt: "2026-04-24T08:12:00+09:00",
  },
  {
    projectId: "proj_lens_guard",
    title: "Optics Guard Housing",
    code: "PF-2421",
    description: "Transparent protective lens cover for environmental bench testing.",
    priority: "medium",
    status: "post_processing",
    ownerUid: "u_eng_talia",
    collaboratorUids: ["u_operator_ivy"],
    requestedMaterialId: "resin_siraya_blu_clear",
    preferredPrinterIds: ["printer_saturn4"],
    dueDate: "2026-04-29T10:00:00+09:00",
    tags: ["resin", "clear-part"],
    blocked: false,
    archived: false,
    progress: 81,
    currentRevisionLabel: "r4 approved_current",
    printerTargetId: "printer_saturn4",
    latestActivityAt: "2026-04-24T07:50:00+09:00",
  },
  {
    projectId: "proj_router_cover",
    title: "Router Safety Cover",
    code: "PF-2424",
    description: "Impact-resistant protective cover for CNC router cable path.",
    priority: "high",
    status: "on_hold",
    ownerUid: "u_eng_owen",
    collaboratorUids: ["u_lead_marcus"],
    requestedMaterialId: "mat_seed_fiberon_pa6_cf20",
    preferredPrinterIds: ["printer_x1e_ops", "printer_x1c_lab1"],
    dueDate: "2026-05-02T15:30:00+09:00",
    tags: ["engineering", "safety"],
    blocked: true,
    archived: false,
    progress: 38,
    currentRevisionLabel: "r2 needs_review",
    printerTargetId: "printer_x1e_ops",
    latestActivityAt: "2026-04-23T18:10:00+09:00",
  },
  {
    projectId: "proj_fixture_cap",
    title: "Calibration Fixture Cap",
    code: "PF-2428",
    description: "Quick-turn cap used in end-of-line calibration routine updates.",
    priority: "medium",
    status: "ready_for_print",
    ownerUid: "u_eng_talia",
    collaboratorUids: ["u_operator_ivy"],
    requestedMaterialId: "mat_seed_bambu_pla_basic",
    preferredPrinterIds: ["printer_a1_bay3", "printer_p1s_cell2"],
    dueDate: "2026-04-30T11:00:00+09:00",
    tags: ["qa", "fast-turn"],
    blocked: false,
    archived: false,
    progress: 63,
    currentRevisionLabel: "r2 approved_current",
    printerTargetId: "printer_a1_bay3",
    latestActivityAt: "2026-04-24T06:42:00+09:00",
  },
  {
    projectId: "proj_packout_tray",
    title: "Packout Tray Prototype",
    code: "PF-2430",
    description: "Visual prototype tray for warehouse handling review.",
    priority: "low",
    status: "design_in_progress",
    ownerUid: "u_eng_owen",
    collaboratorUids: ["u_viewer_sam"],
    requestedMaterialId: "mat_seed_esun_pla_plus",
    preferredPrinterIds: ["printer_a1_bay3"],
    dueDate: "2026-05-05T16:00:00+09:00",
    tags: ["warehouse", "prototype"],
    blocked: false,
    archived: false,
    progress: 21,
    currentRevisionLabel: "r1 drafting",
    printerTargetId: "printer_a1_bay3",
    latestActivityAt: "2026-04-23T12:10:00+09:00",
  },
];

export const seedRevisions: FileRevision[] = [
  {
    revisionId: "rev_jig_r5",
    fileArtifactId: "artifact_jig_main",
    projectId: "proj_jig_panel",
    filename: "panel-alignment-jig_r5.3mf",
    sizeBytes: 24832012,
    uploadedBy: "u_eng_talia",
    uploadedAt: "2026-04-24T07:55:00+09:00",
    revisionNumber: 5,
    status: "approved_current",
    slicer: "Bambu Studio",
    printerProfile: "P1S 0.4 nozzle",
    materialProfile: "PETG HF",
    notes: "Updated support interfaces and reduced infill on base plate.",
    parsedMetadata: {
      slicerDetected: "bambu_studio",
      plateCount: 2,
      materialProfileRaw: "PETG HF",
      printerProfileRaw: "P1S 0.4 nozzle",
      estimateTimeRaw: "6h 20m",
      embeddedThumbnail: true,
      parseConfidence: "high",
    },
    isCurrent: true,
  },
  {
    revisionId: "rev_fixture_r3",
    fileArtifactId: "artifact_fixture_main",
    projectId: "proj_fixture_large",
    filename: "large-fixture-nest_r3.3mf",
    sizeBytes: 48290210,
    uploadedBy: "u_eng_owen",
    uploadedAt: "2026-04-24T07:40:00+09:00",
    revisionNumber: 3,
    status: "ready",
    slicer: "Orca Slicer",
    printerProfile: "K2 Plus 0.6 nozzle",
    materialProfile: "PLA Pro",
    notes: "Large-format split merged into single print strategy.",
    parsedMetadata: {
      slicerDetected: "orca_slicer",
      plateCount: 1,
      materialProfileRaw: "PLA Pro",
      printerProfileRaw: "K2 Plus 0.6 nozzle",
      estimateTimeRaw: "11h 40m",
      embeddedThumbnail: true,
      parseConfidence: "medium",
    },
    isCurrent: true,
  },
  {
    revisionId: "rev_lens_r4",
    fileArtifactId: "artifact_lens_main",
    projectId: "proj_lens_guard",
    filename: "optics-guard-clear_r4.3mf",
    sizeBytes: 12842033,
    uploadedBy: "u_eng_talia",
    uploadedAt: "2026-04-23T16:15:00+09:00",
    revisionNumber: 4,
    status: "approved_current",
    slicer: "Chitubox",
    printerProfile: "Saturn 4 Ultra 16K",
    materialProfile: "Siraya Tech Blu",
    notes: "Clearance tweak around sensor lip before post-process validation.",
    parsedMetadata: {
      slicerDetected: "unknown",
      plateCount: 1,
      materialProfileRaw: "Siraya Tech Blu",
      printerProfileRaw: "Saturn 4 Ultra 16K",
      estimateTimeRaw: "3h 15m",
      embeddedThumbnail: false,
      parseConfidence: "medium",
    },
    isCurrent: true,
  },
  {
    revisionId: "rev_router_r2",
    fileArtifactId: "artifact_router_main",
    projectId: "proj_router_cover",
    filename: "router-safety-cover_r2.3mf",
    sizeBytes: 22291002,
    uploadedBy: "u_eng_owen",
    uploadedAt: "2026-04-23T17:15:00+09:00",
    revisionNumber: 2,
    status: "needs_review",
    slicer: "Bambu Studio",
    printerProfile: "X1E hardened nozzle",
    materialProfile: "Fiberon PA6-CF20",
    notes: "Awaiting confirmation on shrink compensation and chamber requirement.",
    parsedMetadata: {
      slicerDetected: "bambu_studio",
      plateCount: 1,
      materialProfileRaw: "Fiberon PA6-CF20",
      printerProfileRaw: "X1E hardened nozzle",
      estimateTimeRaw: "8h 55m",
      embeddedThumbnail: true,
      parseConfidence: "high",
    },
    isCurrent: true,
  },
  {
    revisionId: "rev_cap_r2",
    fileArtifactId: "artifact_cap_main",
    projectId: "proj_fixture_cap",
    filename: "fixture-cap_r2.3mf",
    sizeBytes: 8124008,
    uploadedBy: "u_eng_talia",
    uploadedAt: "2026-04-24T06:15:00+09:00",
    revisionNumber: 2,
    status: "approved_current",
    slicer: "Bambu Studio",
    printerProfile: "A1 0.4 nozzle",
    materialProfile: "PLA Basic",
    notes: "Signed off for fast-turn calibration batch.",
    parsedMetadata: {
      slicerDetected: "bambu_studio",
      plateCount: 3,
      materialProfileRaw: "PLA Basic",
      printerProfileRaw: "A1 0.4 nozzle",
      estimateTimeRaw: "1h 05m",
      embeddedThumbnail: true,
      parseConfidence: "high",
    },
    isCurrent: true,
  },
];

export const seedBuildJobs: BuildJob[] = [
  {
    buildJobId: "job_jig_244",
    projectId: "proj_jig_panel",
    projectFileRevisionId: "rev_jig_r5",
    printerId: "printer_p1s_cell2",
    materialId: "mat_seed_bambu_petg_hf",
    assignedToUid: "u_operator_ivy",
    queuedAt: "2026-04-24T06:20:00+09:00",
    startedAt: "2026-04-24T07:05:00+09:00",
    jobStatus: "printing",
    quantityPlanned: 2,
    quantityCompleted: 1,
    estimatedPrintTimeMinutes: 380,
    estimatedMaterialUsedGrams: 164,
    notes: "Second article running after first-part dimensional pass.",
  },
  {
    buildJobId: "job_fixture_991",
    projectId: "proj_fixture_large",
    projectFileRevisionId: "rev_fixture_r3",
    printerId: "printer_k2_plus",
    materialId: "mat_seed_polymaker_pla_pro",
    assignedToUid: "u_operator_ivy",
    queuedAt: "2026-04-24T07:10:00+09:00",
    jobStatus: "queued",
    quantityPlanned: 1,
    quantityCompleted: 0,
    estimatedPrintTimeMinutes: 700,
    estimatedMaterialUsedGrams: 492,
    notes: "Waiting on final support verification before launch.",
  },
  {
    buildJobId: "job_lens_842",
    projectId: "proj_lens_guard",
    projectFileRevisionId: "rev_lens_r4",
    printerId: "printer_saturn4",
    materialId: "resin_siraya_blu_clear",
    assignedToUid: "u_operator_ivy",
    queuedAt: "2026-04-24T05:50:00+09:00",
    startedAt: "2026-04-24T06:30:00+09:00",
    endedAt: "2026-04-24T09:05:00+09:00",
    jobStatus: "completed",
    outcome: "success",
    quantityPlanned: 3,
    quantityCompleted: 3,
    estimatedPrintTimeMinutes: 195,
    actualPrintTimeMinutes: 155,
    estimatedMaterialUsedGrams: 86,
    actualMaterialUsedGrams: 79,
    notes: "Transferred to wash/cure and transparency check.",
  },
  {
    buildJobId: "job_cover_731",
    projectId: "proj_router_cover",
    projectFileRevisionId: "rev_router_r2",
    printerId: "printer_sv08",
    materialId: "mat_seed_fiberon_pa6_cf20",
    assignedToUid: "u_operator_ivy",
    queuedAt: "2026-04-23T14:10:00+09:00",
    startedAt: "2026-04-23T15:00:00+09:00",
    jobStatus: "paused",
    quantityPlanned: 1,
    quantityCompleted: 0,
    estimatedPrintTimeMinutes: 535,
    estimatedMaterialUsedGrams: 202,
    notes: "Paused after suspected layer shift during internal ribbing section.",
  },
  {
    buildJobId: "job_cap_112",
    projectId: "proj_fixture_cap",
    projectFileRevisionId: "rev_cap_r2",
    printerId: "printer_a1_bay3",
    materialId: "mat_seed_bambu_pla_basic",
    assignedToUid: "u_operator_ivy",
    queuedAt: "2026-04-24T08:00:00+09:00",
    jobStatus: "assigned",
    quantityPlanned: 4,
    quantityCompleted: 0,
    estimatedPrintTimeMinutes: 72,
    estimatedMaterialUsedGrams: 48,
    notes: "Next up after quick nozzle purge.",
  },
];

export const seedActivity: ActivityEvent[] = [
  {
    eventId: "evt_101",
    entityType: "file",
    entityId: "rev_jig_r5",
    projectId: "proj_jig_panel",
    actorUid: "u_eng_talia",
    actionType: "revision.approved",
    message: "Approved current revision r5 for Panel Alignment Jig.",
    createdAt: "2026-04-24T08:40:00+09:00",
  },
  {
    eventId: "evt_102",
    entityType: "build_job",
    entityId: "job_jig_244",
    projectId: "proj_jig_panel",
    actorUid: "u_operator_ivy",
    actionType: "job.started",
    message: "Started printing on P1S Cell 2 using PETG HF.",
    createdAt: "2026-04-24T07:05:00+09:00",
  },
  {
    eventId: "evt_103",
    entityType: "build_job",
    entityId: "job_lens_842",
    projectId: "proj_lens_guard",
    actorUid: "u_operator_ivy",
    actionType: "job.completed",
    message: "Completed clear housing run on Saturn Resin 1.",
    createdAt: "2026-04-24T09:05:00+09:00",
  },
  {
    eventId: "evt_104",
    entityType: "printer",
    entityId: "printer_x1e_ops",
    actorUid: "u_admin_rina",
    actionType: "printer.maintenance",
    message: "Opened maintenance window for X1E chamber fan inspection.",
    createdAt: "2026-04-24T08:15:00+09:00",
  },
  {
    eventId: "evt_105",
    entityType: "build_job",
    entityId: "job_cover_731",
    projectId: "proj_router_cover",
    actorUid: "u_operator_ivy",
    actionType: "job.paused",
    message: "Paused print on SV08 Alpha after possible layer shift.",
    createdAt: "2026-04-23T16:20:00+09:00",
  },
  {
    eventId: "evt_106",
    entityType: "project",
    entityId: "proj_fixture_large",
    projectId: "proj_fixture_large",
    actorUid: "u_lead_marcus",
    actionType: "blocker.created",
    message: "Flagged support strategy blocker for Large Fixture Nest.",
    createdAt: "2026-04-24T08:12:00+09:00",
  },
];

export const seedBlockers: Blocker[] = [
  {
    blockerId: "blk_fixture_supports",
    projectId: "proj_fixture_large",
    title: "Support strategy needs sign-off before 11h run.",
    severity: "high",
    status: "in_progress",
    assignedToUid: "u_lead_marcus",
    createdByUid: "u_lead_marcus",
    createdAt: "2026-04-24T08:12:00+09:00",
  },
  {
    blockerId: "blk_router_shrink",
    projectId: "proj_router_cover",
    title: "Shrink compensation and chamber temp still unverified.",
    severity: "high",
    status: "open",
    assignedToUid: "u_eng_owen",
    createdByUid: "u_lead_marcus",
    createdAt: "2026-04-23T17:25:00+09:00",
  },
  {
    blockerId: "blk_router_pause",
    projectId: "proj_router_cover",
    title: "Investigate layer shift on SV08 Alpha before retry.",
    severity: "medium",
    status: "waiting",
    assignedToUid: "u_operator_ivy",
    createdByUid: "u_operator_ivy",
    createdAt: "2026-04-23T16:20:00+09:00",
  },
];
